# .readthedocs.yaml

version: 2

build:
  os: ubuntu-22.04

sphinx:
  configuration: docs/source/conf.py

python:
  version: "3.10"
  install:
    - method: pip
      path: .
    - requirements: docs/requirements.txt
